project_id = "rugbunseyblzapwzevqh"

[functions.create-user]
verify_jwt = true

[functions.meta-ads-sync]
verify_jwt = false

[functions.google-ads-sync]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.import-vehicles]
verify_jwt = true

[functions.import-vehicle-photos]
verify_jwt = true

[functions.update-user-auth]
verify_jwt = true

[functions.sync-users]
verify_jwt = true

[functions.generate-report]
verify_jwt = false
